---
- name: deploy dicbio
  become: yes
  hosts: django
  vars:
    django_name: "dicbio"
    django_dest: "/var/www/dicbio"
    django_repo: "https://github.com/fflch/dicbio.git"
    django_version: "main"
    django_port: "8004"
    django_envfile: '.env.sample'
    django_pythonversion: '3.10'
    django_collectstatic: True
    django_wsgi: dicbio
    django_env:
      - name: DEBUG
        value: False
      - name: SECRET_KEY
        value: "123dZdRASw"
      - name: MYSQL_USER
        value: dicbio
      - name: MYSQL_NAME
        value: dicbio
      - name: MYSQL_HOST
        value: 192.168.8.10
      - name: MYSQL_PASSWORD
        value: "dicbio"
      - name: ALLOWED_HOSTS
        value: "*"
      - name: DJANGO_ENV
        value: "production"

  tasks:

    - name: dicbio.fflch.usp.br
      include_role:
        name: fflch.django

    - name: manage.py extract_corpus_terms
      shell: "{{ django_dest }}/venv/bin/python{{ django_pythonversion }} manage.py extract_corpus_terms --force-regen"
      args:
        chdir: "{{ django_dest }}"

    - name: manage.py import_obra_metadata
      shell: "{{ django_dest }}/venv/bin/python{{ django_pythonversion }} manage.py import_obra_metadata"
      args:
        chdir: "{{ django_dest }}"

    - name: manage.py processar_obras_tei
      shell: "{{ django_dest }}/venv/bin/python{{ django_pythonversion }} manage.py processar_obras_tei --force"
      args:
        chdir: "{{ django_dest }}"

    - name: manage.py import_dictionary_data
      shell: "{{ django_dest }}/venv/bin/python{{ django_pythonversion }} manage.py import_dictionary_data"
      args:
        chdir: "{{ django_dest }}"
