---
- name: deploy Drupal
  become: yes
  hosts: drupal
  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks
      vars:
#        tasks_php: true
        tasks_drupal: true
        tasks_php_version: '7.4'

# Entradas no /etc/hosts da hospedeira:
# 192.168.8.44 drupal.local.fflch.usp.br
# 192.168.8.44 lero.local.fflch.usp.br
# 192.168.8.44 sce.local.fflch.usp.br
# 192.168.8.44 sti.local.fflch.usp.br
