---
- name: mariadbmaster
  become: yes
  hosts: mariadbmaster

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_databases: true

    - name: Instala Mysql e cria dbs/users
      include_role:
        name: geerlingguy.mysql
      vars:
        mysql_packages:
          - mariadb-client
          - mariadb-server
        mysql_daemon: mariadb
        mysql_root_username: root
        mysql_root_password: "SuperPassw0rd"
        mysql_bind_address: '*'
        mysql_mysqldump_max_allowed_packet: "1024M"
        mysql_users:
          - name: aegir_root
            host: "%"
            password: "SuperPassw0rd"
            priv: "*.*:ALL,GRANT"

          - name: freeradius
            host: "%"
            password: "freeradius"
            priv: "freeradius.*:ALL"

          - name: copaco
            host: "%"
            password: "copaco"
            priv: "copaco.*:ALL"

          - name: dados
            host: "%"
            password: "dados"
            priv: "dados.*:ALL"

          - name: map
            host: "%"
            password: "map"
            priv: "map.*:ALL"

          - name: dicbio
            host: "%"
            password: "dicbio"
            priv: "dicbio.*:ALL"

          - name: ocsinventoryserver
            host: "%"
            password: "ocsinventoryserver"
            priv: "ocsinventoryserver.*:ALL"

        mysql_databases:
           - name: freeradius
           - name: copaco
           - name: dados
           - name: map
           - name: dicbio
           - name: ocsinventoryserver
