# For Mônica

https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server/

https://daniel.scota.com.br/2018/ocs-inventory-instalacao-e-configuracao/

ansible-playbook playbooks/dev/mariadbmaster.yml


vagrant ssh ocsinventoryserver
apt update

apt install apache2 mariadb-client libxml-simple-perl libdbi-perl libdbd-mysql-perl libapache-dbi-perl libnet-ip-perl libsoap-lite-perl libarchive-zip-perl make build-essential php-pclzip make build-essential libdbd-mysql-perl libnet-ip-perl libxml-simple-perl php php-mbstring php-soap php-mysql php-curl php-xml php-zip php-gd libswitch-perl

apt-get install libxml-simple-perl
apt-get install libio-compress-perl
apt-get install libdbi-perl
apt-get install libdbd-mysql-perl
apt-get install libapache-dbi-perl
apt-get install libnet-ip-perl
apt-get install libsoap-lite-perl
apt-get install libarchive-zip-perl
apt-get install libapache2-mod-perl2-dev

apt-get install libxml-simple-perl libio-compress-perl libdbi-perl libdbd-mysql-perl libapache-dbi-perl libnet-ip-perl libsoap-lite-perl libarchive-zip-perl libapache2-mod-perl2-dev

apt-get install libphp-pclzip
apt-get install php-gd 
apt-get install php-curl php-xml php-soap php-mysql php-zip
apt-get install php-mbstring
apt-get install php-net-ldap


cpan -i XML::Entities
cpan -i Compress::Zlib
cpan -i Apache::SOAP
cpan -i Apache2::SOAP
cpan -i XML::Entities Compress::Zlib Apache2::SOAP


cpan install XML::Entities
cpan Mojolicious
cpan Plack::Handler


Importante: it is possible to provide a setup.answers file with default configuration.

https://github.com/OCSInventory-NG/OCSInventory-ocsreports/tags

https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/2.12.3/OCSNG_UNIX_SERVER-2.12.3.tar.gz

cd OCSInventory-Server
sh setup.sh


/etc/init.d/apache2 restart ou systemctl restart apache2
a2enconf ocsinventory-reports
a2enconf z-ocsinventory-server
chown -R www-data:www-data /var/lib/ocsinventory-reports/
/etc/init.d/apache2 restart ou systemctl restart apache2

http://192.168.8.5/ocsreports